name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_job_running_in_container:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_24_x86_64
    strategy:
      fail-fast: false
    steps:
    - name: say hello
      shell: bash
      run: echo hello!
    - name: pushd
      shell: bash
      run: pushd /tmp
    - name: deps
      run: |
        set -x \
        && apt-get update -qq \
        && apt-get install -qq -y --no-install-recommends \
        make checkinstall build-essential dpkg-dev \
        libreadline-dev libncursesw5-dev libbz2-dev \
        libsqlite3-dev tk-dev libgdbm-dev libc6-dev \
        libffi-dev zlib1g-dev curl liblzma-dev xz-utils \
        libxml2-dev libxmlsec1-dev liblzma-dev \
        git wget upx ca-certificates \
        && apt-get clean -qq \
        && rm -rf /var/lib/apt/list/*
    - name: openssl 1.1.1
      shell: bash
      run: |
        set -x \
        && apt-get remove -qq -y libssl-dev \
        && wget -q https://www.openssl.org/source/openssl-1.1.1.tar.gz \
        && tar -xzf openssl-1.1.1.tar.gz \
        && pushd openssl-1.1.1 \
        && ./config --prefix=${OPENSSL_DIR} --openssldir=${OPENSSL_DIR} shared zlib > /dev/null \
        && make > /dev/null \
        && make install > /dev/null \
        && popd \
        && rm -rf openssl-1.1.1 openssl-1.1.1.tar.gz
    - name: pyenv
      shell: bash
      run: |
        curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash \
        && CPPFLAGS="-O2 -I${OPENSSL_DIR}/include" CFLAGS="-I${OPENSSL_DIR}/include" \
            LD_FLAGS="-L${OPENSSL_DIR}/lib -Wl,-rpath,${OPENSSL_DIR}/lib" LD_RUN_PATH="${OPENSSL_DIR}/lib" \
            CONFIGURE_OPTS="--with-openssl=${OPENSSL_DIR}" PYTHON_CONFIGURE_OPTS="--enable-shared" \
            /root/.pyenv/bin/pyenv install ${PYTHON_LAST} \
        && /root/.pyenv/bin/pyenv global ${PYTHON_LAST}

    - uses: actions/upload-artifact@v2
      with:
        name: log4j-finder-linux.zip
        path: dist/linux/log4j-finder
