name: Nuitka tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - main
      - develop
      - factory
      - release/**
      - hotfix/**

jobs:
  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python_version:
            - '3.10'
    name: Ubuntu Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Nuitka dependencies
        run: |
          sudo apt-get update
          sudo apt-get install chrpath gdb ccache libfuse2
          python -m pip install -r requirements-devel.txt
      - name: Install Nuitka
        run:
          python -m pip install nuitka

      - name: Verbose scons output in compilation
        run: |
          python -m nuitka --show-scons --standalone --onefile --assume-yes-for-downloads test.py
          #python -m nuitka --show-scons --standalone --run test.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/heads/')
        with:
          name: artefacts
          path: |
            test

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python_version:
          #- '2.7'
              #- '3.7'
              #- '3.8'
            - '3.9'
            # TODO: The orderedset wheel doesn't build yet, either disable that
            # or find an alternative.
            # - '3.10'
    name: Windows Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Nuitka dependencies
        run: |
          pip install -r requirements-devel.txt
      - name: Install Nuitka
        run: |
          pip install nuitka
      - name: Verbose scons output in compilation
        run: |
          python -m nuitka --show-scons --standalone --onefile --assume-yes-for-downloads test.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/heads/')
        with:
          name: artefacts
          path: |
            test.exe
